import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage } from "@/components/content/layout";
import { postEntry } from "@/lib/content";

const entry = postEntry("what-is-a-build-sequence");

export const metadata: Metadata = { title: entry.title, description: entry.description, alternates: { canonical: `/blog/${entry.slug}` } };

export default function WhatIsABuildSequencePage(): React.ReactNode {
  return <ContentPage eyebrow="BLOG" title="What is a Build Sequence" lede="Most people hand an AI build tool a prompt and hope. A Build Sequence replaces the hope with structure: one base prompt, a fixed order of follow-ups, and a check at every step.">
    <div className="content-meta"><span>{entry.date}</span><span>{entry.author}</span></div>
    <section><h2>The definition</h2><p>A Build Sequence is one base prompt plus 2 to 12 ordered follow-up prompts, all generated from a Build Understanding you have read, edited, and approved. The base prompt sits at order 0 and establishes the foundation. Each follow-up assumes the state the previous prompts produced and extends it. Every prompt in the sequence states its purpose, includes completion checks you can run before advancing, and traces back to named features in the approved understanding.</p><p>That is the whole idea. It is small enough to explain in a paragraph and strict enough to change how a build goes.</p></section>
    <section><h2>Why the order exists</h2><p>AI build tools do their best work when each request carries a bounded amount of intent. Ask for one working slice and the tool can hold the whole request in view, make consistent decisions, and land on something you can inspect. Ask for an entire product and the tool starts trading your requirements against each other in ways you cannot see.</p><p>The order in a Build Sequence is not presentation. It is the dependency structure of the build. Authentication before profiles, data model before the views that read it, the core flow before the settings that tune it. Each step stands on the ones before it, which is why the sequence is fixed rather than a menu.</p></section>
    <section><h2>The base prompt</h2><p>Order 0 is a complete prompt on its own. It sets up the product’s structure and the first working slice, phrased in the vocabulary of the build target you chose. If you stopped after the base prompt, you would still have something real running. That matters, because the most common failure in AI-assisted building is never reaching a working state at all.</p></section>
    <section><h2>Checks and lineage</h2><p>Every prompt carries completion checks: concrete observations about what should now exist or work. A page that renders, a record that saves, a flow you can click through. Run them before moving on. If a check fails, the failure is local to one step, and the fix is small. Skip the check and the failure compounds into everything built on top of it.</p><p>Each prompt also maps to named features in the approved Build Understanding. You can look at any step and see which approved features it implements, and look at any approved feature and see which step builds it. Nothing in the sequence is unaccounted for, and nothing you approved is silently dropped.</p></section>
    <section><h2>Prompts versus a discipline</h2><p>A pile of prompts is what you get from pasting whatever seems useful into a build tool. A Build Sequence is a discipline: intent is verified before anything is generated, the work is decomposed along its real dependencies, every step has a purpose you can read and a check you can run, and the whole thing is accountable to a document you approved.</p><p>The prompts are the artifact. The discipline is the product.</p><p>This also changes what a failed build means. Without a sequence, a failed build is a verdict on you or on the tool. With one, it is information: a specific check on a specific step, with an approved document to measure the output against. You can disagree with a step, trace it to the feature that produced it, and decide whether the feature or the step is wrong. That conversation is impossible with a pile of prompts, because there is nothing to have it about.</p></section>
    <section><h2>Where to go deeper</h2><p>The reference documentation covers the mechanics in detail, including how follow-ups relate to licensing and what happens when your scope changes after approval. Start with <Link href="/docs/build-sequences">the Build Sequences doc</Link>.</p></section>
  </ContentPage>;
}
