import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Brand } from "@/components/brand";

export const metadata: Metadata = { title: "Privacy Policy", description: "How VibesClone collects, uses, and protects information.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage(): React.ReactNode {
  return <main className="legal-page"><header className="legal-header"><Brand /><Link href="/"><ArrowLeft size={14} /> Back to VibesClone</Link></header><article className="legal-document"><span>LEGAL · EFFECTIVE 13 AUGUST 2026</span><h1>Privacy Policy</h1><p>How VibesClone handles information when you visit the site or use the product.</p>
    <section><h2>Information we collect</h2><p>We collect account details you provide, product and reference URLs, niche and USP inputs, edits to your Build Understanding, generated prompts, purchase and entitlement records, newsletter consent, sponsor or sales inquiries, and basic technical logs. Payment card details are collected and processed by our payment provider, not stored by VibesClone.</p></section>
    <section><h2>How we use it</h2><p>We use this information to authenticate you, analyze the public sources you submit, generate and save your build materials, operate project licensing, prevent abuse, support the service, respond to inquiries, and improve reliability and product experience.</p></section>
    <section><h2>AI and service providers</h2><p>Submitted URLs, extracted public content, and your project instructions may be processed by contracted hosting, extraction, AI, authentication, analytics, email, and payment providers solely to operate VibesClone. Our current product stack includes Railway, Clerk, Dodo Payments, Microsoft Clarity, Resend, and replaceable extraction and AI providers. Their processing is governed by their own terms and our agreements with them.</p></section>
    <section><h2>Public build reports</h2><p>Projects are private by default. If you choose to publish a build report, its product name, source website, niche, USP, approved summary, target users, jobs, flows, and feature decisions become available at a public link. Your account, evidence, payment records, provider details, and prompt sequence are not included. You can make the report private again from the workspace.</p></section>
    <section><h2>Analytics and cookies</h2><p>We use necessary authentication and security storage, plus Microsoft Clarity to understand aggregate navigation and conversion behavior. Sensitive workspace content is masked from session analytics. We also record an allowlisted set of product funnel events, such as blueprint views, remix starts, public-report actions, newsletter signups, and prompt copies. These event records do not store an IP address, prompt text, or free-form project input. You can limit optional analytics through browser privacy controls where supported.</p></section>
    <section><h2>Email choices</h2><p>When you join the digest, we store your normalized email address, consent source, consent time, and an unsubscribe token. Every digest email will include an unsubscribe link. Transactional account, purchase, or service messages may still be sent when necessary to operate your account.</p></section>
    <section><h2>Retention and security</h2><p>We retain project and account data while your account is active and as reasonably needed for support, fraud prevention, tax, legal, and operational records. We use access controls and industry-standard service providers, but no internet service can guarantee absolute security.</p></section>
    <section><h2>Your choices</h2><p>You can unpublish or delete individual projects in the workspace and unsubscribe from the digest in one step. To request access, correction, export, account deletion, or ask a privacy question, email <a href="mailto:sales@vibesclone.com">sales@vibesclone.com</a>. We may need to verify your identity before completing a request.</p></section>
    <section><h2>Children and changes</h2><p>VibesClone is not directed to children under 13. We may update this policy as the service changes and will publish the revised effective date here.</p></section>
  </article></main>;
}
