import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage } from "@/components/content/layout";

export const metadata: Metadata = { title: "Why mega-prompts fail", description: "The failure modes of describing an entire product in one prompt, and what verification before generation fixes about each of them.", alternates: { canonical: "/blog/why-mega-prompts-fail" } };

export default function WhyMegaPromptsFailPage(): React.ReactNode {
  return <ContentPage eyebrow="BLOG" title="Why mega-prompts fail" lede="The 4,000-word prompt that describes your whole product feels thorough. It is actually the least controlled way to run a build, and its failures are predictable enough to name.">
    <div className="content-meta"><span>2026-07-30</span><span>VibesClone</span></div>
    <section><h2>Hidden misunderstandings</h2><p>A mega-prompt is generated once and pasted once. Whatever the tool misread about your intent is baked into everything it produces, and you discover the misreading only by inspecting the output. By then the wrong assumption has touched the data model, the flows, and half the interface. You are not correcting a sentence anymore. You are unwinding a building.</p><p>The fix is structural, not stylistic. Intent has to be verified before generation, in a form you can read and edit. When the analysis is a document you approve rather than a prompt you fire, misunderstandings surface while they still cost nothing.</p></section>
    <section><h2>Default-filling</h2><p>No prompt specifies everything, and a mega-prompt hides which parts it left open. The tool fills every gap with defaults: generic auth, generic empty states, a settings page nobody asked for. The result reads as plausible, which is worse than reading as wrong. You ship someone else’s median product with your name on it and cannot point to the line where that happened.</p></section>
    <section><h2>Feature interference</h2><p>Ask for twelve features in one request and the tool trades them against each other silently. The notification system constrains the data model, which constrains the search, which quietly narrows what the export can do. Each compromise is individually reasonable and collectively unaccountable. Features built one step at a time cannot interfere this way, because each step lands on a working state before the next one begins.</p></section>
    <section><h2>No checkpoint to localize failure</h2><p>When a single prompt produces the entire build and something is broken, which part of the prompt caused it? There is no answer, because there is no boundary anywhere in the process. Debugging becomes archaeology. Ordered steps with completion checks give every failure a home: the check that failed points at the step that failed, and the fix stays the size of one step.</p></section>
    <section><h2>Drift</h2><p>Long generations drift. The conventions established early in the output loosen by the end. Naming shifts, patterns fork, the last feature described is built to a different standard than the first. This is not a defect of any particular tool. It is what happens when one request is asked to hold more intent than any single pass can carry. Bounded steps reset the frame each time, so the fortieth minute of the build is as controlled as the first.</p><p>Drift is also the failure people misdiagnose most. The early output looks strong, so the prompt gets credit; the late output degrades, so the tool gets blame. Neither is the cause. The request shape is, and no amount of rewording a 4,000-word prompt changes its shape.</p></section>
    <section><h2>The alternative, precisely</h2><p>The alternative is not shorter prompts or better prompt-writing tips. It is a different order of operations. First, an editable analysis of what you are building: the features to retain, modify, and add, stated plainly enough to argue with. You approve it, and the approval is a snapshot the rest of the build answers to. Then generation happens as a sequence: one base prompt that establishes a working foundation, followed by ordered follow-ups, each with a purpose and checks, each traceable to features you approved.</p><ul><li>Misunderstandings surface in the document, not the build.</li><li>Gaps are visible before defaults fill them.</li><li>Features arrive one at a time, so they cannot silently trade against each other.</li><li>Every failure localizes to a step.</li></ul></section>
    <section><h2>Further reading</h2><p>The approval mechanism that makes this work is covered in <Link href="/docs/build-understanding">The Build Understanding</Link>.</p></section>
  </ContentPage>;
}
