// Generated from the Startup Marketplace Intelligence snapshot (TrustMRR, AppSumo, Acquire) taken 2026-09-05.
// Revenue figures are TrustMRR-verified MRR at snapshot time, rounded to the nearest $100. Regenerate rather than hand-edit.

export type Competition = "Low" | "Medium" | "High";

export type Opportunity = {
  slug: string;
  name: string;
  website: string;
  trustmrrUrl: string;
  category: string;
  mrr: number;
  growth30d: number | null;
  founded: string | null;
  founderFollowers: number;
  audience: string | null;
  pricing: string | null;
  persona: string | null;
  summary: string;
  problem: string | null;
  onSale: boolean;
  askingPrice: number | null;
  competition: Competition;
  categoryEarningCount: number;
};

export type BetterVersion = { name: string; tagline: string; purchases: number; rating: number; reviews: number; category: string; appsumoUrl: string; productUrl: string | null };

export const marketStats = {
  "snapshotDate": "2026-09-05",
  "trustmrrStartups": 10290,
  "withRevenue": 4360,
  "over1k": 951,
  "over10k": 233,
  "midBand": 906,
  "midBandSmallAudienceShare": 0.76,
  "midBandMedianFollowers": 79,
  "recentSmallAudience": 444,
  "recentSmallAudienceMedianMrr": 2900,
  "forSaleOver1k": 318,
  "forSaleMedianAsk": 117500,
  "forSaleMedianMultiple": 2.4,
  "acquireListings": 1241,
  "acquireSmallCount": 490,
  "acquireSmallMedianAsk": 97800,
  "acquireSmallMedianMultiple": 1.8,
  "appsumoProducts": 4238,
  "appsumoPaidButPoorlyRated": 326
} as const;

export const opportunities: readonly Opportunity[] = [
  {
    "slug": "rankai",
    "name": "RankAI",
    "website": "https://rankai.ai/",
    "trustmrrUrl": "https://trustmrr.com/startup/rankai",
    "category": "Marketing",
    "mrr": 57100,
    "growth30d": 23.4,
    "founded": "2023-06",
    "founderFollowers": 79,
    "audience": "B2B",
    "pricing": "For Businesses: Expert-led SEO + AI search strategy. For Agencies: Recurring revenue with near-zero overhead. Self-serve plan available.",
    "persona": "Agencies and Ecommerce Businesses",
    "summary": "Get search visitors autonomously. RankAI runs autonomously – getting you millions of web visitors from Google & ChatGPT. Investors from YCombinator, OpenAI, A16z, etc.",
    "problem": null,
    "onSale": false,
    "askingPrice": null,
    "competition": "Medium",
    "categoryEarningCount": 113
  },
  {
    "slug": "dropkiller",
    "name": "Dropkiller",
    "website": "https://www.dropkiller.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/dropkiller",
    "category": "E-comm",
    "mrr": 51300,
    "growth30d": 37.7,
    "founded": "2024-10",
    "founderFollowers": 0,
    "audience": "B2B",
    "pricing": null,
    "persona": "Entrepreneurs in Latin America",
    "summary": "We offer a subscription-based service that provides e-commerce entrepreneurs with access to product insights, ad creatives, and market analysis tools. Customers are charged at checkout or on a…",
    "problem": "Helps entrepreneurs find winning products and make data-driven decisions to maximize sales.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 32
  },
  {
    "slug": "llm-gateway",
    "name": "LLM Gateway",
    "website": "https://llmgateway.io/",
    "trustmrrUrl": "https://trustmrr.com/startup/llm-gateway",
    "category": "AI",
    "mrr": 47200,
    "growth30d": 239.5,
    "founded": "2025-05",
    "founderFollowers": 1265,
    "audience": "B2B",
    "pricing": "Free tier included",
    "persona": "Developers",
    "summary": "LLM Gateway is an open-source API gateway for Large Language Models (LLMs). It acts as a middleware between your applications and various LLM providers, allowing you to: - Route requests to multiple…",
    "problem": "Eliminates the need to juggle multiple API keys and provider dashboards by offering a unified API interface.",
    "onSale": false,
    "askingPrice": null,
    "competition": "High",
    "categoryEarningCount": 545
  },
  {
    "slug": "uhoh-com",
    "name": "uhoh.com",
    "website": "https://uhoh.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/uhoh-com",
    "category": "Customer Support",
    "mrr": 36900,
    "growth30d": 21.4,
    "founded": "2025-06",
    "founderFollowers": 245,
    "audience": "B2B",
    "pricing": "Starting at $3k/mo, up to 50 staff",
    "persona": "Growing businesses and startups",
    "summary": "The first IT help desk that's free to try and priced by you.",
    "problem": "Solves tech issues for growing businesses, allowing them to focus on their core activities without being slowed down by technical problems.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 10
  },
  {
    "slug": "conductor",
    "name": "Conductor",
    "website": "https://conductor.is/",
    "trustmrrUrl": "https://trustmrr.com/startup/conductor",
    "category": "Dev Tools",
    "mrr": 35400,
    "growth30d": 9.6,
    "founded": "2022-07",
    "founderFollowers": 1007,
    "audience": "B2B",
    "pricing": "Trial: Free, Production: $49 per company file per month, Enterprise: Tailored pricing",
    "persona": "Developers working with QuickBooks Desktop & Enterprise",
    "summary": "The best QuickBooks Desktop & Enterprise API on the planet.",
    "problem": "Conductor completely abstracts away the fragility and quirks of QuickBooks Desktop, the Web Connector, qbXML, SOAP, and more.",
    "onSale": true,
    "askingPrice": 1250000,
    "competition": "Low",
    "categoryEarningCount": 73
  },
  {
    "slug": "rank-prompt",
    "name": "Rank Prompt",
    "website": "https://rankprompt.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/rank-prompt",
    "category": "AI",
    "mrr": 29900,
    "growth30d": -16.6,
    "founded": "2025-05",
    "founderFollowers": 29,
    "audience": "Both",
    "pricing": "Starter (150/mo), Pro (500/mo), Agency (1000/mo)",
    "persona": "SaaS startups, global enterprises, e-commerce brands, professional services, healthcare, finance, real estate, agencies",
    "summary": "Rank Prompt helps users understand how their website shows up on AI Search Engines and how to improve it. AEO (AI SEO).",
    "problem": "Brands need to optimize their AI visibility as AI platforms fundamentally change how consumers discover brands.",
    "onSale": false,
    "askingPrice": null,
    "competition": "High",
    "categoryEarningCount": 545
  },
  {
    "slug": "droppop",
    "name": "DropPop",
    "website": "https://droppop.io/",
    "trustmrrUrl": "https://trustmrr.com/startup/droppop",
    "category": "SaaS",
    "mrr": 27800,
    "growth30d": -0.3,
    "founded": "2025-05",
    "founderFollowers": 176,
    "audience": "B2C",
    "pricing": "$4.99 First Month Only",
    "persona": "Dropshippers on platforms like Depop, Vinted, Etsy, eBay, and Amazon",
    "summary": "The #1 Dropshipping Tool to Automate Depop, Vinted, Etsy and Ebay with AI. Your all-in-one tool for automating listings, generating descriptions, changing images, and fulfilling orders seamlessly.",
    "problem": "Eliminates the biggest time-waster in Depop dropshipping by automating order processing and management.",
    "onSale": true,
    "askingPrice": 55000,
    "competition": "Medium",
    "categoryEarningCount": 150
  },
  {
    "slug": "produce-so",
    "name": "Produce.so",
    "website": "https://produce.so/",
    "trustmrrUrl": "https://trustmrr.com/startup/produce-so",
    "category": "Content Creation",
    "mrr": 27400,
    "growth30d": 0.0,
    "founded": "2025-11",
    "founderFollowers": 4683,
    "audience": "B2C",
    "pricing": "Creator: $149/mo, Pro: $329/mo, Elite Plan: $497/mo",
    "persona": "Faceless YouTube Channel Creators",
    "summary": "AI tool for creating long-form videos and scripts for YouTube channels.",
    "problem": "Automates the creation of ultra-long-form YouTube videos and scripts, significantly reducing the time and effort required for content creators.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Medium",
    "categoryEarningCount": 91
  },
  {
    "slug": "backlinker-ai",
    "name": "Backlinker AI",
    "website": "https://backlinker.ai/",
    "trustmrrUrl": "https://trustmrr.com/startup/backlinker-ai",
    "category": "Marketing",
    "mrr": 27000,
    "growth30d": 5.3,
    "founded": "2023-07",
    "founderFollowers": 0,
    "audience": "B2B",
    "pricing": "$300/mo",
    "persona": "Businesses looking to improve SEO through automated backlink generation",
    "summary": "Backlinker AI automates backlink acquisition through AI-powered reporter and editorial outreach. Built for agencies, founders, and SEO teams, it finds relevant opportunities, drafts responses, and…",
    "problem": "Automating reporter outreach for backlink generation to boost domain authority and search rankings.",
    "onSale": true,
    "askingPrice": 350000,
    "competition": "Medium",
    "categoryEarningCount": 113
  },
  {
    "slug": "atlas",
    "name": "Atlas",
    "website": "https://www.atlas.org/",
    "trustmrrUrl": "https://trustmrr.com/startup/atlas",
    "category": "AI",
    "mrr": 26700,
    "growth30d": -5.8,
    "founded": "2024-08",
    "founderFollowers": 0,
    "audience": "B2C",
    "pricing": "Free",
    "persona": "Students",
    "summary": "Atlas is a personalized learning platform for students. Atlas's AI studies your class materials to help you nail your homework and ace your tests.",
    "problem": "Helping students achieve better grades with powerful, AI-driven tools.",
    "onSale": true,
    "askingPrice": 1250000,
    "competition": "High",
    "categoryEarningCount": 545
  },
  {
    "slug": "adstellar",
    "name": "AdStellar",
    "website": "https://www.adstellar.ai/",
    "trustmrrUrl": "https://trustmrr.com/startup/adstellar",
    "category": "AI",
    "mrr": 26000,
    "growth30d": 25.5,
    "founded": "2025-10",
    "founderFollowers": 2105,
    "audience": "B2B",
    "pricing": "Start 7-day free trial",
    "persona": "Top marketing teams",
    "summary": "Launch Meta ads 10x faster & find winning ad combos with 10x less ad budget.",
    "problem": "Frustration with Meta Ads Manager due to its inefficiency in handling rapid testing and creative variations.",
    "onSale": false,
    "askingPrice": null,
    "competition": "High",
    "categoryEarningCount": 545
  },
  {
    "slug": "stack-influence",
    "name": "Stack Influence",
    "website": "https://stackinfluence.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/stack-influence",
    "category": "Marketing",
    "mrr": 25700,
    "growth30d": 8.1,
    "founded": "2020-01",
    "founderFollowers": 900,
    "audience": "B2B",
    "pricing": "$30 flat fee, $500 flat fee + Platform Fees, $100 flat fee + 8% Payout Creator Negotiation, Added monthly fees $0, $6K/mo (annual contract), $499/mo, $1,799/mo",
    "persona": "eCommerce brands",
    "summary": "Micro Creator marketing platform for eComm brands.",
    "problem": "Simplifying and automating the process of influencer marketing for brands.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Medium",
    "categoryEarningCount": 113
  },
  {
    "slug": "cosmo",
    "name": "Cosmo",
    "website": "https://www.visitcosmo.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/cosmo",
    "category": "E-comm",
    "mrr": 25600,
    "growth30d": null,
    "founded": "2023-06",
    "founderFollowers": 428,
    "audience": null,
    "pricing": null,
    "persona": null,
    "summary": "The all-in-one commerce platform for Discord. Sell, automate, and grow natively inside your server.",
    "problem": null,
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 32
  },
  {
    "slug": "seo-stack",
    "name": "SEO STACK",
    "website": "https://www.seo-stack.io/",
    "trustmrrUrl": "https://trustmrr.com/startup/seo-stack",
    "category": "SaaS",
    "mrr": 25500,
    "growth30d": -1.6,
    "founded": "2021-01",
    "founderFollowers": 3260,
    "audience": "B2B",
    "pricing": "Single Site: $19.99/mo, Lite: $69.99/mo, Basic: $139.99/mo, Pro: $279.99/mo, Agency: $489.99/mo",
    "persona": "SEO Professionals, Businesses, Agencies",
    "summary": "SEO stack is an SEO/marketing SaaS that offers data warehousing with AI. It is a rebuild of Google search console with Google analytics, it allows SEOs and marketers to get better results in search…",
    "problem": "Warehousing, accessing, and interacting with Search Console data without limitations.",
    "onSale": true,
    "askingPrice": 1000000,
    "competition": "Medium",
    "categoryEarningCount": 150
  },
  {
    "slug": "talefy",
    "name": "Talefy",
    "website": "https://talefy.ai/",
    "trustmrrUrl": "https://trustmrr.com/startup/talefy",
    "category": "Games",
    "mrr": 25000,
    "growth30d": -2.1,
    "founded": "2023-05",
    "founderFollowers": 1152,
    "audience": "B2C",
    "pricing": "The price start from just $1.99",
    "persona": "Writers, readers, gamers, or dreamers",
    "summary": "AI-Powered Interactive Story Games. Immerse Yourself in Endless Possibilities",
    "problem": "Helps users overcome writer's block and offers tools to create or explore interactive stories.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 17
  },
  {
    "slug": "debatium",
    "name": "Debatium",
    "website": "https://apps.apple.com/app/id6444075752",
    "trustmrrUrl": "https://trustmrr.com/startup/debatium",
    "category": "Entertainment",
    "mrr": 23700,
    "growth30d": 0.0,
    "founded": null,
    "founderFollowers": 163,
    "audience": "B2C",
    "pricing": "Weekly subscription $8.99, Weekly subscription $5.99, Premium mode (happy hour) $3.99",
    "persona": "Couples looking to enhance their relationship through engaging and meaningful conversations.",
    "summary": "Debatium is a conversation game app for couples to explore various topics and deepen their bond.",
    "problem": "Helps couples engage in meaningful conversations and explore topics they might not usually discuss, thereby strengthening their relationship.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 27
  },
  {
    "slug": "marky",
    "name": "Marky",
    "website": "https://mymarky.ai/",
    "trustmrrUrl": "https://trustmrr.com/startup/marky",
    "category": "Content Creation",
    "mrr": 22700,
    "growth30d": -9.0,
    "founded": "2023-07",
    "founderFollowers": 64,
    "audience": "B2B",
    "pricing": "Free trial available, no credit card required",
    "persona": "Local service-based businesses, healthcare practices, professional services firms, home services companies, retail and…",
    "summary": "A tool for self-publishing authors to manage their social media.",
    "problem": "Helps businesses generate, schedule, and publish branded content efficiently across multiple social media platforms.",
    "onSale": true,
    "askingPrice": 495000,
    "competition": "Medium",
    "categoryEarningCount": 91
  },
  {
    "slug": "chatseo",
    "name": "ChatSEO",
    "website": "https://chatseo.app/",
    "trustmrrUrl": "https://trustmrr.com/startup/chatseo",
    "category": "SaaS",
    "mrr": 22200,
    "growth30d": 1.1,
    "founded": "2025-11",
    "founderFollowers": 4508,
    "audience": "B2B",
    "pricing": "Free to start — no credit card required",
    "persona": "SEO Consultants, E-commerce Site Owners, Novice SEOs, Freelance SEOs, Campsite Managers",
    "summary": "Find & prioritize your SEO wins by chatting with your data.",
    "problem": null,
    "onSale": false,
    "askingPrice": null,
    "competition": "Medium",
    "categoryEarningCount": 150
  },
  {
    "slug": "groups-watcher",
    "name": "Groups Watcher",
    "website": "https://www.groupswatcher.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/groups-watcher",
    "category": "Marketing",
    "mrr": 21400,
    "growth30d": 19.7,
    "founded": "2024-07",
    "founderFollowers": 56,
    "audience": "B2B",
    "pricing": "$49 (intro offer), $499 (business plan)",
    "persona": null,
    "summary": "Ready-to-pay leads are asking for your services in Facebook groups right now. Groups Watcher alerts you within 60 seconds, so you get to them first.",
    "problem": "Facebook groups are a goldmine of leads, but there was no way to monitor them without paying $2,000 to $3,000 a month for manual labor. GroupsWatcher automates it, scanning your niche's groups and…",
    "onSale": true,
    "askingPrice": 500000,
    "competition": "Medium",
    "categoryEarningCount": 113
  },
  {
    "slug": "trackai",
    "name": "TrackAI",
    "website": "https://trackai.app/",
    "trustmrrUrl": "https://trustmrr.com/startup/trackai",
    "category": "Mobile Apps",
    "mrr": 20900,
    "growth30d": 0.0,
    "founded": "2025-06",
    "founderFollowers": 67,
    "audience": "B2C",
    "pricing": "Freemium; auto-renewing subscriptions: weekly, monthly and annual plans \"$5.99/week, $9.99/month, $42.99/year\")",
    "persona": "Health-conscious people aged 25–45 in Ukraine and CEE who want to lose or mainta",
    "summary": "TrackAI is an AI calorie tracking app for iOS and Android: snap a photo of your meal and instantly get calories and macros. For busy people to stay consistent. Launched June 2025, it grew to $20k MRR…",
    "problem": "Removes the tedious manual food logging that makes people quit calorie tracking within days",
    "onSale": true,
    "askingPrice": 300000,
    "competition": "Medium",
    "categoryEarningCount": 139
  },
  {
    "slug": "leadshark",
    "name": "LeadShark",
    "website": "https://www.leadshark.io/",
    "trustmrrUrl": "https://trustmrr.com/startup/leadshark",
    "category": "Marketing",
    "mrr": 20800,
    "growth30d": -4.8,
    "founded": "2024-05",
    "founderFollowers": 453,
    "audience": "B2B",
    "pricing": "Pro: $39/mo, Pro+: $59/mo, Apex: $119/mo",
    "persona": "LinkedIn users looking to automate lead generation",
    "summary": "Lead Magnets on Auto-Pilot // The original Lead Magnet Automation for LinkedIn // 22K+ posts automated // 2.5M DMs sent Turn every comment into a lead. Deliver your lead magnet instantly to people…",
    "problem": "Engagement that doesn't convert: Your posts get comments, but DMs take hours. You can't reply fast enough, which kills post growth and misses potential customer conversions.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Medium",
    "categoryEarningCount": 113
  },
  {
    "slug": "brevilabs",
    "name": "Brevilabs",
    "website": "https://brevilabs.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/brevilabs",
    "category": "AI",
    "mrr": 20400,
    "growth30d": -4.4,
    "founded": "2025-01",
    "founderFollowers": 2092,
    "audience": "B2C",
    "pricing": null,
    "persona": "Obsidian users",
    "summary": "Tools for any AI agent to access and manage your personal context",
    "problem": "Leverage intelligent agent equipped with tools to truly understand your Obsidian vault while preserving privacy with local data storage.",
    "onSale": false,
    "askingPrice": null,
    "competition": "High",
    "categoryEarningCount": 545
  },
  {
    "slug": "vuely-inc",
    "name": "Vuely",
    "website": "https://vuely.co/",
    "trustmrrUrl": "https://trustmrr.com/startup/vuely-inc",
    "category": "AI",
    "mrr": 19200,
    "growth30d": -10.8,
    "founded": "2026-04",
    "founderFollowers": 3,
    "audience": "B2B",
    "pricing": "Basic: $249/mo, Pro: $699/mo, Business: $1,499/mo, Enterprise: Custom",
    "persona": "Signage professionals and sign shops",
    "summary": "Vuely is an AI-powered platform automating the mockup design and bidding process for sign companies.",
    "problem": "Cut surveys, mockups, and proposals from days down to minutes, helping signage professionals close more deals and earn more.",
    "onSale": false,
    "askingPrice": null,
    "competition": "High",
    "categoryEarningCount": 545
  },
  {
    "slug": "lancer-app",
    "name": "Lancer.app",
    "website": "https://www.lancer.app/",
    "trustmrrUrl": "https://trustmrr.com/startup/lancer-app",
    "category": "Sales",
    "mrr": 17900,
    "growth30d": 1.5,
    "founded": "2025-04",
    "founderFollowers": 67,
    "audience": "B2C",
    "pricing": "Pay-Per-Lead: $99/mo, Unlimited: $333/mo",
    "persona": "Freelancers and agencies",
    "summary": "Lancer.app is an AI-powered tool that automates job application process on Upwork for freelancers and agencies.",
    "problem": "Automate Upwork outreach and never miss an opportunity.",
    "onSale": true,
    "askingPrice": 699999,
    "competition": "Low",
    "categoryEarningCount": 26
  },
  {
    "slug": "draft-ai",
    "name": "Draft AI",
    "website": "https://getdraft.io/",
    "trustmrrUrl": "https://trustmrr.com/startup/draft-ai",
    "category": "Content Creation",
    "mrr": 17400,
    "growth30d": 0.0,
    "founded": null,
    "founderFollowers": 155,
    "audience": "B2C",
    "pricing": "Try it for free",
    "persona": null,
    "summary": "Draft AI turns voice recordings into social media posts and scripts",
    "problem": "Struggling with content on social media?",
    "onSale": false,
    "askingPrice": null,
    "competition": "Medium",
    "categoryEarningCount": 91
  },
  {
    "slug": "autocontent-api",
    "name": "AutoContent API",
    "website": "https://autocontentapi.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/autocontent-api",
    "category": "Content Creation",
    "mrr": 17000,
    "growth30d": 0.4,
    "founded": "2024-10",
    "founderFollowers": 230,
    "audience": "B2B",
    "pricing": "Amateur: $33/mo, Professional: $66/mo, Business: $124/mo",
    "persona": "Content creators, developers, and businesses seeking automated content solutions",
    "summary": "AutoContent API provides an API for automated content generation across multiple formats.",
    "problem": "Eliminates the manual effort and time required for content creation by automating the process, ensuring content is always fresh and relevant.",
    "onSale": true,
    "askingPrice": 1200000,
    "competition": "Medium",
    "categoryEarningCount": 91
  },
  {
    "slug": "aiwritebook",
    "name": "AIWriteBook",
    "website": "https://aiwritebook.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/aiwritebook",
    "category": "Content Creation",
    "mrr": 16700,
    "growth30d": 0.0,
    "founded": "2025-12",
    "founderFollowers": 0,
    "audience": "B2C",
    "pricing": "Start Your Book Free. No credit card required.",
    "persona": "Authors, KDP Publishers, Prolific Authors, First-Time Authors, Self-Help & Spiritual Authors, Children's Book Creators",
    "summary": "AIWriteBook is an all-in-one AI book creation platform used by 15,700+ authors to go from idea to published book in hours - not months. Start from scratch or import an existing manuscript (.docx…",
    "problem": "One tool replaces your entire writing workflow. Start from scratch or import your existing draft. Stop juggling 5-7 separate tools. Everything you need to write, design, and publish—in one place.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Medium",
    "categoryEarningCount": 91
  },
  {
    "slug": "leverage",
    "name": "Leverage",
    "website": "https://leverage.immo/",
    "trustmrrUrl": "https://trustmrr.com/startup/leverage",
    "category": "Real Estate",
    "mrr": 16200,
    "growth30d": 29.7,
    "founded": "2024-04",
    "founderFollowers": 422,
    "audience": "B2C",
    "pricing": "Starter: 12 €/year, Plus: 228 €/year, Pro: 348 €/year, Ultimate: 2988 €/year",
    "persona": "Real estate investors",
    "summary": "Leverage combines property search, deal analysis, and AI-powered valuation into a clear result: Within minutes, you’ll know whether a property is worth pursuing—and what to do next.",
    "problem": "Property purchases rarely fail because of the property. They fail because of the process.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 13
  },
  {
    "slug": "setsmart",
    "name": "SetSmart",
    "website": "https://setsmart.io/",
    "trustmrrUrl": "https://trustmrr.com/startup/setsmart",
    "category": "SaaS",
    "mrr": 15700,
    "growth30d": 100.0,
    "founded": "2024-06",
    "founderFollowers": 0,
    "audience": "B2C",
    "pricing": "$97/month",
    "persona": "Online coaches, fitness, weight-loss and nutrition coaches, course creators, business/make-money coaches",
    "summary": "AI sales setter that automatically qualifies your leads and books calls via Instagram DMs and WhatsApp. Custom scripts, smart filtering, direct calendar booking, 24/7. Integrates with Calendly, GHL…",
    "problem": "Reply too slowly and your leads go cold, then ghost you for good.",
    "onSale": true,
    "askingPrice": 499000,
    "competition": "Medium",
    "categoryEarningCount": 150
  },
  {
    "slug": "bookedin",
    "name": "Bookedin",
    "website": "https://bookedin.ai/",
    "trustmrrUrl": "https://trustmrr.com/startup/bookedin",
    "category": "Sales",
    "mrr": 15100,
    "growth30d": 6.1,
    "founded": "2023-06",
    "founderFollowers": 2192,
    "audience": "B2B",
    "pricing": "Starter: $75/mo, Pro: $208/mo, Agency: $291/mo",
    "persona": "Agencies and businesses that want to sell AI automation without coding.",
    "summary": "BookedIn ai is a no-code AI platform agencies use to create and manage AI receptionists and sales agents across voice, SMS, email, and messaging apps like Instagram. These agents can instantly engage…",
    "problem": "Implementing AI solutions requires stitching together multiple tools, which is complex and time-consuming, creating a bottleneck for businesses.",
    "onSale": true,
    "askingPrice": 1000000,
    "competition": "Low",
    "categoryEarningCount": 26
  },
  {
    "slug": "controlresell",
    "name": "ControlResell",
    "website": "https://controlresell.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/controlresell",
    "category": "E-comm",
    "mrr": 14200,
    "growth30d": 21.0,
    "founded": "2025-01",
    "founderFollowers": 444,
    "audience": "B2C",
    "pricing": "Starter: 19,99€/month, Growth: 29,99€/month, Business: 59,99€/month, Enterprise: 119,99€/month",
    "persona": "Resellers on platforms like Vinted, Shopify, eBay, and others",
    "summary": "ControlResell is a monthly subscription software that allows resellers to track all their sales and purchases. We have a YouTube channel with tens of thousands of views, a podcast, and a recognized…",
    "problem": "Save time and automate sales processes for resellers.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 32
  },
  {
    "slug": "sermon-scribe",
    "name": "Sermon Scribe",
    "website": "https://sermonscribe.app/",
    "trustmrrUrl": "https://trustmrr.com/startup/sermon-scribe",
    "category": "Mobile Apps",
    "mrr": 14200,
    "growth30d": -0.4,
    "founded": "2025-01",
    "founderFollowers": 0,
    "audience": "B2C",
    "pricing": "Free to try with premium features available.",
    "persona": "Believers, Bible Study Participants, Small Group Leaders",
    "summary": "Record. Transcribe. Summarize. Your all-in-one faith companion.",
    "problem": "Preserve spiritual moments and never miss key sermon insights.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Medium",
    "categoryEarningCount": 139
  },
  {
    "slug": "icollect-everything-all-apps",
    "name": "iCollect Everything",
    "website": "https://apps.apple.com/app/id559036969",
    "trustmrrUrl": "https://trustmrr.com/startup/icollect-everything-all-apps",
    "category": "Productivity",
    "mrr": 13700,
    "growth30d": 0.0,
    "founded": null,
    "founderFollowers": 1648,
    "audience": "B2C",
    "pricing": "Free · In‑App Purchases",
    "persona": "Collectors, School Teachers, Individuals with large inventories",
    "summary": "iCollect Everything is the #1 app on the App Store for managing your collectibles or inventory, whether at home, business, work, or school.",
    "problem": "Helps users manage and inventory a wide range of collections with ease, providing a centralized platform to organize and track collectibles.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Medium",
    "categoryEarningCount": 95
  },
  {
    "slug": "magicslides-app",
    "name": "MagicSlides.app",
    "website": "https://www.magicslides.app/",
    "trustmrrUrl": "https://trustmrr.com/startup/magicslides-app",
    "category": "Education",
    "mrr": 13500,
    "growth30d": -6.1,
    "founded": "2023-01",
    "founderFollowers": 3974,
    "audience": "B2C",
    "pricing": "Premium: $29/month billed monthly, Premium Plus: $34/month billed monthly",
    "persona": "Professionals",
    "summary": "MagicSlides next-gen AI presentation tool, converts any prompt, topic, or content source into a professional PPT in seconds.",
    "problem": "Converts ideas, prompts, documents, or videos into ready-to-use presentations instantly.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 82
  },
  {
    "slug": "hirevire",
    "name": "Hirevire",
    "website": "https://hirevire.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/hirevire",
    "category": "Recruiting & HR",
    "mrr": 13000,
    "growth30d": 0.1,
    "founded": "2021-12",
    "founderFollowers": 2226,
    "audience": "B2B",
    "pricing": "7-day free trial · No credit card required",
    "persona": "HR Managers, Talent Acquisition Leads, People Operations, Founder/CEOs, Global Talent Acquisition, Remote-First…",
    "summary": "Screen 3x more candidates in half the time with one way video interviews",
    "problem": "Candidate screening is broken due to scheduling conflicts, productivity interruptions, and loss of critical information.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 21
  },
  {
    "slug": "imposter-ai",
    "name": "imposter․ai",
    "website": "https://apps.apple.com/app/id6754861642",
    "trustmrrUrl": "https://trustmrr.com/startup/imposter-ai",
    "category": "Games",
    "mrr": 12400,
    "growth30d": 0.0,
    "founded": "2025-12",
    "founderFollowers": 278,
    "audience": "B2C",
    "pricing": "Free, with in-app purchases: Imposter Pro — Annual $29.99, Monthly $4.99, Weekly $4.99, and more.",
    "persona": "Groups of friends and family looking for a fun party game.",
    "summary": "imposter.ai is the social deduction party game where bluffing and guessing collide — now with Party Mode, Online Play, and AI-powered categories.",
    "problem": "Provides endless fun and social interaction through a party game that combines bluffing and deduction.",
    "onSale": true,
    "askingPrice": 300000,
    "competition": "Low",
    "categoryEarningCount": 17
  },
  {
    "slug": "synta",
    "name": "Synta",
    "website": "https://synta.io/",
    "trustmrrUrl": "https://trustmrr.com/startup/synta",
    "category": "SaaS",
    "mrr": 11400,
    "growth30d": -16.4,
    "founded": "2025-09",
    "founderFollowers": 0,
    "audience": "B2B",
    "pricing": "Start with a 3-day free trial of Standard. $34 Per month, billed monthly. $67 Per month, billed monthly. Contact Sales.",
    "persona": "Individual developers and small teams, growing teams and businesses, large teams and organizations.",
    "summary": "A premium model context protocol (MCP) server and web app designed to turn AI clients like Claude, Cursor, and OpenClaw into expert n8n workflow architects, with over 300+ businesses using it daily…",
    "problem": "Stop firefighting broken workflows. Synta MCP triggers test runs, reads live output from every node, pinpoints what failed, and rewrites the config — iterating until every execution passes.",
    "onSale": true,
    "askingPrice": 100000,
    "competition": "Medium",
    "categoryEarningCount": 150
  },
  {
    "slug": "nutria",
    "name": "nutrIA",
    "website": "https://apps.apple.com/app/id6744851977",
    "trustmrrUrl": "https://trustmrr.com/startup/nutria",
    "category": "Mobile Apps",
    "mrr": 10700,
    "growth30d": 0.0,
    "founded": "2025-04",
    "founderFollowers": 0,
    "audience": "B2C",
    "pricing": "Free: $0/mo, In-App Purchases available",
    "persona": "People interested in health and fitness, looking to improve their eating habits",
    "summary": "nutrIA is an AI-powered nutrition app focused on habit tracking, personalized feedback and daily engagement. The app combines food recognition, smart recommendations and gamified challenges to drive…",
    "problem": "Helps users eat better by providing instant calorie and macronutrient estimates of their meals.",
    "onSale": true,
    "askingPrice": 700000,
    "competition": "Medium",
    "categoryEarningCount": 139
  },
  {
    "slug": "everythingweather",
    "name": "EverythingWeather",
    "website": "https://everythingwx.com/",
    "trustmrrUrl": "https://trustmrr.com/startup/everythingweather",
    "category": "Mobile Apps",
    "mrr": 10600,
    "growth30d": 0.0,
    "founded": null,
    "founderFollowers": 4548,
    "audience": "B2C",
    "pricing": "Free with Pro subscription for additional features",
    "persona": "Weather enthusiasts and individuals needing detailed weather information",
    "summary": "A US and Canada Only Weather app with the most accurate forecasts available.",
    "problem": "Delivers forecast data directly from the National Weather Service, ensuring it's intuitive and easy to understand.",
    "onSale": true,
    "askingPrice": 1600000,
    "competition": "Medium",
    "categoryEarningCount": 139
  },
  {
    "slug": "3ak-track-field",
    "name": "3AK Track & Field",
    "website": "https://apps.apple.com/app/id6756290066",
    "trustmrrUrl": "https://trustmrr.com/startup/3ak-track-field",
    "category": "Health & Fitness",
    "mrr": 10100,
    "growth30d": 0.0,
    "founded": "2025-12",
    "founderFollowers": 1081,
    "audience": "B2C",
    "pricing": "In-App Purchases: Yearly $39.99, Yearly $29.99, Monthly $9.99, Weekly Pro $9.99, Weekly $6.99",
    "persona": "Track & field athletes and competitive runners",
    "summary": "The #1 Track and Field Training app. It helps athletes fix their form and run new PR's by giving personalized training.",
    "problem": "3AK provides athletes with tools, coaching, and structure that used to be reserved for pro athletes, helping them to train smarter and achieve real results.",
    "onSale": true,
    "askingPrice": 350000,
    "competition": "Medium",
    "categoryEarningCount": 96
  },
  {
    "slug": "formo",
    "name": "Formo",
    "website": "https://formo.so/",
    "trustmrrUrl": "https://trustmrr.com/startup/formo",
    "category": "Analytics",
    "mrr": 9700,
    "growth30d": -3.0,
    "founded": "2024-09",
    "founderFollowers": 1758,
    "audience": "B2B",
    "pricing": "Start for free",
    "persona": "Crypto startups, onchain builders, DeFi product managers",
    "summary": "Analytics and attribution for DeFi apps. Measure what matters and drive growth onchain with the data platform for crypto and DeFi. Formo makes analytics and attribution easy for onchain apps, so you…",
    "problem": "Using other tools with onchain data was clunky for analytics, especially in web3.",
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 44
  },
  {
    "slug": "threadcam",
    "name": "ThreadCam",
    "website": "https://apps.apple.com/app/id6755987135",
    "trustmrrUrl": "https://trustmrr.com/startup/threadcam",
    "category": "Design Tools",
    "mrr": 9400,
    "growth30d": 0.0,
    "founded": "2025-12",
    "founderFollowers": 1822,
    "audience": "B2C",
    "pricing": "Free · In‑App Purchases",
    "persona": "Streetwear brands, print-on-demand sellers, designers, band merch creators, startups, anyone with a clothing idea",
    "summary": "ThreadCam allows user to create 3D mockups of their tshirt/garment designs. Mainly iOS app, just launched android app.",
    "problem": "Visualize designs on photorealistic 3D models before production.",
    "onSale": true,
    "askingPrice": 200000,
    "competition": "Low",
    "categoryEarningCount": 32
  },
  {
    "slug": "showroompro-ai",
    "name": "ShowroomPro.ai",
    "website": "https://showroompro.ai/",
    "trustmrrUrl": "https://trustmrr.com/startup/showroompro-ai",
    "category": "E-comm",
    "mrr": 8400,
    "growth30d": -3.0,
    "founded": "2026-02",
    "founderFollowers": 336,
    "audience": "B2B",
    "pricing": null,
    "persona": "Independent jewelry brands and custom designers",
    "summary": "We provide software for jewelry brands and designers to offer their clients an interactive way to design jewelry, including but not limited to, engagement and wedding rings.",
    "problem": null,
    "onSale": false,
    "askingPrice": null,
    "competition": "Low",
    "categoryEarningCount": 32
  }
];

export const betterVersions: readonly BetterVersion[] = [
  {
    "name": "Intellifluence",
    "tagline": "Find influencers, create campaigns, and boost awareness in one easy-to-use platform",
    "purchases": 45781,
    "rating": 3.38,
    "reviews": 24,
    "category": "influencer ugc",
    "appsumoUrl": "https://appsumo.com/products/intellifluence/",
    "productUrl": "https://intellifluence.com/"
  },
  {
    "name": "SEO SpyGlass",
    "tagline": "Track, analyze, and replicate competitor backlinks to boost your SEO strategy",
    "purchases": 38117,
    "rating": 3.67,
    "reviews": 27,
    "category": "software",
    "appsumoUrl": "https://appsumo.com/products/seo-spyglass/",
    "productUrl": "https://www.link-assistant.com/seo-spyglass/"
  },
  {
    "name": "KingSumo",
    "tagline": "Grow your audience with viral giveaways that cut marketing costs",
    "purchases": 23860,
    "rating": 3.83,
    "reviews": 65,
    "category": "lead capture forms",
    "appsumoUrl": "https://appsumo.com/products/kingsumo/",
    "productUrl": "https://kingsumo.com/"
  },
  {
    "name": "TrackMySubs",
    "tagline": "Declutter your subscriptions and take control of your recurring payments",
    "purchases": 17488,
    "rating": 3.84,
    "reviews": 32,
    "category": "software",
    "appsumoUrl": "https://appsumo.com/products/trackmysubs/",
    "productUrl": "http://www.trackmysubs.com"
  },
  {
    "name": "Process Street",
    "tagline": "Manage and streamline repeatable checklists and procedures",
    "purchases": 11038,
    "rating": 3.36,
    "reviews": 25,
    "category": "software",
    "appsumoUrl": "https://appsumo.com/products/process-street-2019/",
    "productUrl": "https://www.process.st/"
  },
  {
    "name": "MailPoet",
    "tagline": "Design and manage award-winning emails inside WordPress",
    "purchases": 10663,
    "rating": 3.77,
    "reviews": 84,
    "category": "software",
    "appsumoUrl": "https://appsumo.com/products/mailpoet/",
    "productUrl": "https://www.mailpoet.com/"
  },
  {
    "name": "QR Diffusion",
    "tagline": "QR Diffusion transforming QR codes into AI-crafted art pieces",
    "purchases": 9958,
    "rating": 3.88,
    "reviews": 16,
    "category": "visual design",
    "appsumoUrl": "https://appsumo.com/products/qr-diffusion/",
    "productUrl": null
  },
  {
    "name": "Sessions",
    "tagline": "Create and host immersive, customer-facing video experiences with one user-friendly platform",
    "purchases": 9692,
    "rating": 3.76,
    "reviews": 309,
    "category": "remote collaboration",
    "appsumoUrl": "https://appsumo.com/products/sessions/",
    "productUrl": "https://sessions.us/"
  },
  {
    "name": "Serpstat",
    "tagline": "The window to see your competition's strategies is closing",
    "purchases": 8176,
    "rating": 3.44,
    "reviews": 48,
    "category": "software",
    "appsumoUrl": "https://appsumo.com/products/serpstat-2018/",
    "productUrl": "https://serpstat.com"
  },
  {
    "name": "Airmeet",
    "tagline": "Host interactive virtual events with a suite of tools to network and build connections",
    "purchases": 7167,
    "rating": 3.63,
    "reviews": 95,
    "category": "software",
    "appsumoUrl": "https://appsumo.com/products/airmeet/",
    "productUrl": "http://www.airmeet.com/"
  },
  {
    "name": "Restream",
    "tagline": "Your bridge to live-streaming across all platforms has arrived",
    "purchases": 6751,
    "rating": 3.99,
    "reviews": 74,
    "category": "software",
    "appsumoUrl": "https://appsumo.com/products/restream/",
    "productUrl": null
  },
  {
    "name": "Email List Validation",
    "tagline": "Clean up all of your email lists to reach the right inbox every time",
    "purchases": 6737,
    "rating": 3.13,
    "reviews": 254,
    "category": "email marketing",
    "appsumoUrl": "https://appsumo.com/products/email-list-validation/",
    "productUrl": "http://emaillistvalidation.com/"
  }
];
